api.listening_addr = "127.0.0.1:5005"
webui.listening_addr = "127.0.0.1:8080"

[[activity_wasm]]
name = "activity_http_generic"
location.oci = "docker.io/getobelisk/components_activity-http-generic_activity_http_generic:2026-01-12-1@sha256:7ca207e5fd0346029f66444298cd14ca6b6e092039e3da63169a3016462004ec"
forward_stdout = "stderr"
forward_stderr = "stderr"
exec.lock_expiry.seconds = 5
