api.listening_addr = "127.0.0.1:5005"
webui.listening_addr = "127.0.0.1:8080"

[[activity_wasm]]
name = "activity_fly_http"
location.oci = "docker.io/getobelisk/components_activity-fly-http_activity_fly_http:2026-01-13@sha256:499b0221a79b29bc436d950e4f6544a957ff0e65d0f07ba90f169d2e0ae61d07"
exec.lock_expiry.seconds = 15
env_vars = ["FLY_API_TOKEN"]
forward_stdout = "stderr"
forward_stderr = "stderr"
