api.listening_addr = "127.0.0.1:5005"
webui.listening_addr = "127.0.0.1:8080"

[[activity_wasm]]
name = "activity_github_graphql"
location.path = "${OBELISK_TOML_DIR}/../../target/wasm32-wasip2/release_activity/activity_github_graphql.wasm"
exec.lock_expiry.seconds = 5
env_vars = ["GITHUB_TOKEN"]
forward_stdout = "stderr"
forward_stderr = "stderr"
